# Generated by Django 4.0.5 on 2022-06-21 16:51

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, default='ORders', max_length=60, verbose_name='Order ID')),
                ('customer_id', models.CharField(blank=True, default='Customer', max_length=60, verbose_name='Customer ID')),
                ('invoice_id', models.CharField(blank=True, default='INvoice', max_length=60, verbose_name='Invoice ID')),
                ('delivery_status', models.CharField(choices=[('offen', 'offen'), ('Bearbeitung', 'Bearbeitung'), ('abgeschlossen', 'abgeschlossen')], default='offen', max_length=20, verbose_name='Delivery Status')),
                ('customer_type', models.CharField(choices=[('Privat', 'Privat'), ('Gewerbe', 'Gewerbe')], default='Privat', max_length=20, verbose_name='Nachsende-Typ')),
                ('order_reason', models.CharField(choices=[('Umzug', 'Umzug'), ('Abwesenheit / Urlaub', 'Abwesenheit / Urlaub'), ('Betreuungsfall', 'Betreuungsfall'), ('Sterbefall', 'Sterbefall'), ('Insolvenz', 'Insolvenz')], default='Umzug', max_length=40, verbose_name='Nachsendegrund')),
                ('order_time', models.CharField(blank=True, max_length=60, null=True, verbose_name='Order Time')),
                ('later_start_time', models.DateField(blank=True, null=True, verbose_name='Nachsende-Start')),
                ('deliver_again_date', models.DateField(blank=True, null=True, verbose_name='Wieder zustellen ab')),
                ('base_price', models.CharField(blank=True, max_length=60, null=True, verbose_name='Grundpreis')),
                ('product_price', models.CharField(blank=True, max_length=60, null=True, verbose_name='Produktpreis')),
                ('other_price', models.CharField(blank=True, max_length=60, null=True, verbose_name='Preis der Dienstleistung')),
                ('product_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Produktname')),
                ('company_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Firma')),
                ('full_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='voller Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('phone_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='Telefon')),
                ('representative_full_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='Bevollmächtigter')),
                ('notice_of_relocation', models.BooleanField(blank=True, default=False, verbose_name='Umzugsmitteilung')),
                ('parcel_shipments', models.BooleanField(blank=True, default=False, verbose_name='Päckchen und Pakete')),
                ('dhl_infopost', models.BooleanField(blank=True, default=False, verbose_name='DHL INFOPOST')),
                ('status_order', models.BooleanField(blank=True, default=False, verbose_name='Status der Bestellung')),
                ('status_invoice', models.BooleanField(blank=True, default=False, verbose_name='Status der Rechnung')),
                ('other_service', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='Weitere Versanddienstleister'), blank=True, null=True, size=None)),
                ('additional_recipients', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='Weitere Person'), blank=True, null=True, size=None)),
                ('address', models.CharField(blank=True, max_length=60, null=True, verbose_name='Adresse')),
                ('address_supplement', models.CharField(blank=True, max_length=60, null=True, verbose_name='Adresszusatz')),
                ('address_additional_pobox', models.CharField(blank=True, max_length=60, null=True, verbose_name='Postfach-Nr.')),
                ('address_additional_zipcode', models.CharField(blank=True, max_length=60, null=True, verbose_name='PLZ')),
                ('address_additional_city', models.CharField(blank=True, max_length=60, null=True, verbose_name='Stadt')),
                ('new_address', models.CharField(blank=True, max_length=60, null=True, verbose_name='neue Adresse')),
                ('new_address_supplement', models.CharField(blank=True, max_length=60, null=True, verbose_name='neue Adresse Adresszusatz')),
                ('new_address_additional_pobox', models.CharField(blank=True, max_length=60, null=True, verbose_name='neue Adresse Postfach-Nr.')),
                ('new_address_additional_zipcode', models.CharField(blank=True, max_length=60, null=True, verbose_name='neue Adresse PLZ')),
                ('new_address_additional_city', models.CharField(blank=True, max_length=60, null=True, verbose_name='neue Adresse Stadt')),
                ('invoice_pdf', models.URLField(blank=True, null=True, verbose_name='PDF-Datei')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='aktualisiert am')),
                ('payment_service', models.CharField(choices=[('PAYPAL', 'PAYPAL'), ('STRIPE', 'STRIPE')], default='PAYPAL', max_length=40, verbose_name='Zahlungsart wählen')),
            ],
        ),
    ]
