# Generated by Django 4.0.5 on 2022-06-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_pdf',
            field=models.URLField(blank=True, null=True, verbose_name='Rechnungsstellung PDF-Datei'),
        ),
    ]
